### ISSUE TITLE
Annual leave doesn't contribute to the time logged this week

### ISSUE THREAD

**Issue by BjohnShawL** [danstewart/log-my-time#19]
![image](https://github.com/danstewart/log-my-time/assets/26646638/e408346f-6b85-47ed-aa36-98028b2219ff)

In core.stats() you work out that the remaining time is equal to todo_this_week - (logged_this_week + leave_this_week)
But you pass the view logged_this_week without accounting for leave, meaning that you end up with a discrepancy == any leave logged. It might be worth changing the left hand column to include any leave

**Comment by danstewart** [comment]
This has been fixed.
![image](https://github.com/user-attachments/assets/053749a5-16fc-4601-9533-fa616d60aa86)
